backend:
  name: git-gateway
  branch: master

media_folder: "/src/data/uploads"
# public_folder: "/src/data"

collections:
  - name: "image"
    folder: "data/_images"
    create: true
    extension: "json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
